#!/bin/bash
# Copyright (c) YugaByte, Inc.

set -euo pipefail

export DEVOPS_HOME="${BASH_SOURCE%/*}"/../devops

. "$DEVOPS_HOME/bin/"/common.sh

print_help() {
  cat <<-EOT
Generates the node agent packages in destination.
Usage: ${0##*/} <options>
Options:
  -h, --help
    Show usage.
  -d, --destination
    Directory into which the binary should be copied.
  -l, --local
    Generate pre-release packages in /opt/yugabyte/node-agent/releases.
  -t, --target
    Set the target platform (linux/amd64 or linux/arm64).  Default is ${ALT_TARGET_NAME}
  -p, --rebuild_pex
    Build ansible only pex for node agent.
EOT
}

readonly node_agent_home=$( cd "${BASH_SOURCE%/*}" && pwd )

destination=""
localbuild=false
pre_release=""
target="${ALT_TARGET_NAME}"
include_pex=""
while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      print_help
      exit 0
    ;;
    -d|--destination)
      destination="$2"
      shift
    ;;
    -l|--local)
      localbuild="true"
    ;;
    -t|--target)
      target="$2"
      shift
    ;;
    -p|--include_pex)
      include_pex="--include_pex"
    ;;
  esac
  shift
done

if $localbuild; then
  pre_release="--pre_release"
  if [[ ! -d $destination ]]; then
    destination="/opt/yugabyte/node-agent/releases"
    mkdir -p "$destination"
  fi
elif [[ ! -d $destination ]]; then
  fatal "No destination directory found ('$destination')"
fi

activate_virtualenv
set -x
$node_agent_home/yb_release.py --source_dir $node_agent_home --destination $destination \
                               $pre_release $include_pex --target "$target"
